### ISSUE TITLE
 Business Card Design

### ISSUE THREAD

**Issue by karnawataman** [opencodeiiita/Lets-Design-3.0#148]
# Business Card Design

This Task is for you to show off your Visual Design Skills and Minimal Thinking. 
A Business Card represents your company's brand. Not only does it convey important personal contact information such as name, title, email, website, address and phone number, but often it is also the first exposure to the overall image of the business.

In this task, you have to design a **Minimal Business card for a Design Company**. Which must have been pretty much clear by the name of the issue. you have to design 

> 💡 This task need be done in **Adobe Illustrator** or **Figma** [ Use standard business card Frame size i.e., 1050 x 600 px ].

## Elements that are necessary to be included but not limited to:

1. Company Logo. 
2. Company mail id: letsdesign@gmail.com
3. Company website: www.letsdesign.com
4. Details of Owner: 
    - Your Name | Your Contact no. | Your mail id
    - For ex. (Aman | 7339865573 | iec2021033@iiita.ac.in)
5. A tag-line [ * not important ]

If you are unclear with how to start, you can check out this article: [https://www.brandly.com/blog/standard-business-card-size/](https://www.brandly.com/blog/standard-business-card-size/) 

or check out this tutorial: [https://www.youtube.com/watch?v=2yAWGpCR_9A](https://www.youtube.com/watch?v=2yAWGpCR_9A)

## Submission Guidelines:

For Submission you would have to provide the *link to the figma frame,* if doing in figma or *Upload the illustrator file*, if doing in Illustrator in a text file and make sure to keep the file in "**Business Card Design Task"** folder only. Also add jpg or png file of your work in the PR.

Any kind of plagiarism will not be supported. You can take inspiration, but the idea must be unique. 

## **MDC (Minimum Design Criteria):**

The business card should obviously look like a business card and not like any other form of print media. Since it is a 30 point task we are expecting proper use of two of the design principles: Alignment and Proximity. This includes visual connection of elements with each other, arrangement of content in logical groups and proper utilisation of white space. The card should not look cluttered, while also not missing on the important contents. It should have extremely well defined order of importance of hierarchy.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by ananyaa07** [comment]
@karnawataman what is the deadline for this task?
