### ISSUE TITLE
Pen tool task-1

### ISSUE THREAD

**Issue by karnawataman** [opencodeiiita/Lets-Design-3.0#49]
# Pen tool Task-1 

**OPEN TO ALL** **No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 21tst December 11:59 P.M.**

After playing with shapes, now it’s time to learn the pen tool, one of the most commonly used tools to make vectors.

In this task, you are supposed to copy the given vector in Illustrator or Figma using the pen tool and submit the Illustrator file (.ai file) or a text file with a Figma link.

> 💡 This task can be done in **Adobe Illustrator or Figma**.

## **Submission Guideline:**

- Submit the illustrator file in the "Pen tool Task-1" Folder only.
- Paste a jpg/png file of your design in the Pull Request.

> This task is for **20 points**.

## **MDC (Minimum Design Criteria):**

In this task you can only submit one PR once submitted you wont get chance to edit. The vector which you are going to copy should look like the vector given.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

![Frame 168](https://user-images.githubusercontent.com/97426868/208735978-9dc8fb6d-6983-42c4-8920-6afea7044a16.png)

**Comment by RibhavBansal** [comment]
claim
