### ISSUE TITLE
Merry Christmas

### ISSUE THREAD

**Issue by karnawataman** [opencodeiiita/Lets-Design-3.0#78]
# Minimal Poster Design-1

**OPEN TO ALL** **No need to claim this issue** **NO SUBMISSION WILL BE ACCEPTED AFTER 23th December 11:59 PM**

In this task you have to make a **Minimal Poster** for **Chritsmas**.

> 💡 This task can be done in **Adobe Illustrator or Figma**.

## Submission Guidelines:

For Submission, you would have to *Upload the illustrator file( if doing in illustrator )* or a *.txt file (with figma link in it)* and make sure to keep the file in the "**Minimal Poster Design-1”** folder only. You need to add a jpg or png file of your work in the PR. 

Any kind of plagiarism will not be supported. You can take inspiration, but the idea must be unique. 

Name of your *illustrator file/ text file* should be your github username

> This task is for **20 points**.

## **MDC (Minimum Design Criteria):**

The Design must be unique. Any kind of plagiarism will not be tolerated. The poster should be minimal and should look like a poster, vectors used should be original.

For any doubts related to the task or the submission process you can always ping us on discord. We will be happy to help.

**Comment by RibhavBansal** [comment]
claim
